version: 1.0.{build}
branches:
  only:
    - /^(release/)?\d+\.\d+\.\d+(-\w*)?$/
    - /^(release/)?\d+\.\d+\.\d+(.\d*)?$/
image: Ubuntu
clone_depth: 1
environment:
  matrix:
    - login:
        secure: P83FI/K74rS7TKPNZvehYojR3qYFtPDnYt5EDBkymRRGzbjWMXPwtNaqVNe9r5v6zfFXZjmjQKU2r8FY9R9wL+d8YCREe/ZCDojvtQ9jGzhkBhMSLOOyFSjqPeQ7pJvz
build_script:
  - sh: docker build compiler/cpp -f build/docker/publish/Dockerfile -t cspwizard/thrift:$APPVEYOR_REPO_BRANCH
  - sh: eval $login
  - sh: docker push cspwizard/thrift:$APPVEYOR_REPO_BRANCH
